// export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST';
export const GET_WEATHER_DATA_SUCCESS = 'GET_WEATHER_DATA_SUCCESS';
export const GET_WEATHER_DATA_ERROR = 'GET_WEATHER_DATA_ERROR';
export const GET_LOCATION = 'GET_LOCATION';
export const GET_GEOCODE_DATA_SUCCESS = 'GET_GEOCODE_DATA_SUCCESS';
export const GET_GEOCODE_DATA_ERROR = 'GET_GEOCODE_DATA_ERROR';